# services:
#   backend:
#     build: .
#     ports:
#       - "3000:3000"
#     depends_on:
#       - mysql
#     environment:
#       - DB_HOST=mysql
#       - DB_USER=root
#       - DB_PASSWORD=root
#       - DB_NAME=majorproject

#   mysql:
#     image: mysql:8
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: majorproject
#     ports:
#       - "3307:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql
#       - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

# volumes:
#   mysql_data:
